# Workflow para actualizar el índice de imágenes manualmente o cuando sea necesario
name: Update Images Index

on:
  workflow_dispatch: # Solo permite ejecutar manualmente

jobs:
  update-index:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Update images index
      run: node scripts/update-images-index.js
      
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/generated-images/images-index.json
        git commit -m "🤖 Auto-update images index [skip ci]"
        git push
        echo "✅ Índice actualizado y pusheado. Vercel hará deploy automáticamente."